"""TMDb API paths in one place."""

BASE_URL = "https://api.themoviedb.org/3"
AUTHENTICATION = "/authentication"
CONFIGURATION = "/configuration"
SEARCH_MOVIE = "/search/movie"
SEARCH_TV = "/search/tv"
DISCOVER_MOVIE = "/discover/movie"
DISCOVER_TV = "/discover/tv"
MOVIE = "/movie/{id}"
MOVIE_CREDITS = "/movie/{id}/credits"
MOVIE_VIDEOS = "/movie/{id}/videos"
MOVIE_SIMILAR = "/movie/{id}/similar"
MOVIE_RECOMMENDATIONS = "/movie/{id}/recommendations"
MOVIE_WATCH_PROVIDERS = "/movie/{id}/watch/providers"
TV = "/tv/{id}"
TV_SEASON = "/tv/{id}/season/{season_number}"
TV_CREDITS = "/tv/{id}/credits"
TV_VIDEOS = "/tv/{id}/videos"
TV_SIMILAR = "/tv/{id}/similar"
TV_RECOMMENDATIONS = "/tv/{id}/recommendations"
TV_WATCH_PROVIDERS = "/tv/{id}/watch/providers"
